### ISSUE TITLE
https://jonovotny.github.io/ is down

### ISSUE THREAD

**Issue by DylanBanta** [jonovotny/fantasy_maptiler#1]
This code still functions fine, but references to https://jonovotny.github.io don't return as expected causing things like the quests to show nothing when toggled.

**Comment by jonovotny** [comment]
I guess it was a casualty from when I moved my webpage away from github.io. The [demo link](https://jonovotny.github.io/map.html) on the project page is up and running again.

However, I am not sure if I can recommend using this project anymore, as it is a bit outdated. The main issue is that tiling the map is only possible for up to 5 or 6 zoom levels before running into internal memory issues with tile generation. At the same time these few zoomlevels generate hundreds of MBs in tiles to store, and zooming from continent to town level would likely require GBs worth of tiles. 

I am currently having more success with using [OpenLayers](https://openlayers.org/), which allows placement of image sources without the need for tiling.

**Comment by DylanBanta** [comment]
Thanks for updating haha, I've messed around with optimizing it for RAM and larger map sizes but I'm not very experienced with python. I'll check out OpenLayers and see if it's a more fitting solution to my needs

**Comment by jonovotny** [comment]
I just pushed my [OpenLayers project repo](https://github.com/jonovotny/dm-map) to github, in case it helps.
It is very barebones, with just some maps placed at the right scales to each other and a few experimental drawing tools for markers.
